In [1]:
import numpy as np
import pandas as pd
import os

In [3]:
curname = 'Far'

## Creating csv with F_N from fixed directions

In [245]:
cip = []
mainpath = r'D:\seva\598_processing' 
for root, directories, filenames in os.walk(mainpath): 
    for filename in filenames:
        if filename[-11:] == '_N_1001.csv':
            cip.append(os.path.join(root,filename))

In [246]:
len(cip)

5270

In [247]:
cip[0]

'D:\\seva\\598_processing\\train\\1484727\\1493208_F_N_1001.csv'

In [248]:
tempar = np.genfromtxt(cip[0], delimiter='\n')  

In [249]:
tempar.shape

(441,)

In [250]:
valar = np.zeros([len(cip),tempar.shape[0]])
for i in range(len(cip)):
    valar[i,:] = np.genfromtxt(cip[i], delimiter=',')    

In [251]:
tmean = np.zeros([4,tempar.shape[0]])
tmean[0,:] = np.mean(valar, axis = 0)
tmean[1,:] = np.std(valar, axis = 0)
tmean[2,:] = np.min(valar, axis = 0)
tmean[3,:] = np.max(valar, axis = 0)
np.savetxt(r'D:/seva/598test/F_N_1001_stat.csv', tmean, delimiter=",")

In [252]:
cip[i][-28:-13]

'1484726\\1493207'

In [9]:
len(cip)

104

In [11]:
cip[0].split('_Y_N')[0]

'/p/home/jusers/cherepashkin1/jureca/cherepashkin1/619csv/train/1524792/1527407'

In [16]:
#D_out = 441
mainpath = '/p/home/jusers/cherepashkin1/jureca/cherepashkin1/619csv'
cip = []
for root, directories, filenames in os.walk(mainpath): 
    for filename in filenames:
        if filename[-11:] == 'Y_N_500.csv':
            cip.append(os.path.join(root,filename))
landmarks_frame = pd.DataFrame()
landmarks_frame.insert(0, 'file_name', \
                       [cip[i].split('_Y_N')[0] for i in range(len(cip))])
landmarks_frame.to_csv(os.path.join(mainpath,'file_pathes.csv'), index=False)


In [14]:
landmarks_frame

file_name
0    /p/home/jusers/cherepashkin1/jureca/cherepashk...
1    /p/home/jusers/cherepashkin1/jureca/cherepashk...
2    /p/home/jusers/cherepashkin1/jureca/cherepashk...
3    /p/home/jusers/cherepashkin1/jureca/cherepashk...
4    /p/home/jusers/cherepashkin1/jureca/cherepashk...
..                                                 ...
99   /p/home/jusers/cherepashkin1/jureca/cherepashk...
100  /p/home/jusers/cherepashkin1/jureca/cherepashk...
101  /p/home/jusers/cherepashkin1/jureca/cherepashk...
102  /p/home/jusers/cherepashkin1/jureca/cherepashk...
103  /p/home/jusers/cherepashkin1/jureca/cherepashk...

[104 rows x 1 columns]

## Creating csv with Far from fixed directions

In [259]:
cip = []
mainpath = r'D:\seva\598_processing' 
for root, directories, filenames in os.walk(mainpath): 
    for filename in filenames:
        if filename[-11:] == 'ar_1001.csv':
            cip.append(os.path.join(root,filename))

In [260]:
len(cip)

5270

In [261]:
cip[0]

'D:\\seva\\598_processing\\train\\1484727\\1493208_Far_1001.csv'

In [262]:
tempar = np.genfromtxt(cip[0], delimiter='\n')  

In [263]:
tempar.shape

(1000,)

In [264]:
valar = np.zeros([len(cip),tempar.shape[0]])
for i in range(len(cip)):
    valar[i,:] = np.genfromtxt(cip[i], delimiter=',')    

In [265]:
tmean = np.zeros([4,tempar.shape[0]])
tmean[0,:] = np.mean(valar, axis = 0)
tmean[1,:] = np.std(valar, axis = 0)
tmean[2,:] = np.min(valar, axis = 0)
tmean[3,:] = np.max(valar, axis = 0)
np.savetxt(r'D:/seva/598test/Far_1001_stat.csv', tmean, delimiter=",")

In [266]:
cip[i][-28:-13]

'1484726\\1493207'

In [267]:
mainpath

'D:\\seva\\598_processing'

In [268]:
#D_out = 441
# if not(os.path.isfile('tmean.csv') and os.path.isfile(mainpath+'/sh.csv')):

landmarks_frame = pd.DataFrame(data=valar,index=range(len(cip)),\
                               columns=['f'+str(i) for i in range(tempar.shape[0])])
landmarks_frame.insert(0, 'file_name', \
                       [cip[i][-28:-13] for i in range(len(cip))])
landmarks_frame.to_csv(r'D:/seva/598test/Far_1001.csv', index=False)


## Creating csv for F_N2 only for train

In [269]:
cip = []
##mainpath = r'D:\seva\598_processing\train' 
mainpath = r'D:\seva\598_processing\train' 
for root, directories, filenames in os.walk(mainpath): 
    for filename in filenames:
        if filename[-11:] == '_N_1001.csv':
            cip.append(os.path.join(root,filename))

In [270]:
len(cip)

4072

In [271]:
tempar = np.genfromtxt(cip[0])
tempar.shape[0]

441

In [272]:
valar = np.zeros([len(cip),tempar.shape[0]])
for i in range(len(cip)):
    valar[i,:] = np.genfromtxt(cip[i], delimiter=',')    

In [273]:
cip[i][-28:-13]

'1484760\\1500861'

In [274]:
#D_out = 441
# if not(os.path.isfile('tmean.csv') and os.path.isfile(mainpath+'/sh.csv')):

landmarks_frame = pd.DataFrame(data=valar,index=range(len(cip)),\
                               columns=['f'+str(i) for i in range(tempar.shape[0])])
landmarks_frame.insert(0, 'file_name', \
                       [cip[i][-28:-13] for i in range(len(cip))])
landmarks_frame.to_csv(r'D:/seva/598test/train/F_N_1001.csv', index=False)


## Creating csv for F_N2 only for val

In [275]:
cip = []
mainpath = r'D:\seva\598_processing\val' 
for root, directories, filenames in os.walk(mainpath): 
    for filename in filenames:
        if filename[-11:] == '_N_1001.csv':
            cip.append(os.path.join(root,filename))

In [276]:
tempar = np.genfromtxt(cip[0])
tempar.shape[0]

441

In [277]:
valar = np.zeros([len(cip),tempar.shape[0]])
for i in range(len(cip)):
    valar[i,:] = np.genfromtxt(cip[i], delimiter=',')    

In [278]:
cip[i][-28:-13]

'1484726\\1493207'

In [279]:
#D_out = 441
# if not(os.path.isfile('tmean.csv') and os.path.isfile(mainpath+'/sh.csv')):

landmarks_frame = pd.DataFrame(data=valar,index=range(len(cip)),\
                               columns=['f'+str(i) for i in range(tempar.shape[0])])
landmarks_frame.insert(0, 'file_name', \
                       [cip[i][-28:-13] for i in range(len(cip))])
landmarks_frame.to_csv(r'D:/seva/598test/val/F_N_1001.csv', index=False)


## Creating csv for Far only for train

In [280]:
cip = []
mainpath = r'D:\seva\598_processing\train' 
for root, directories, filenames in os.walk(mainpath): 
    for filename in filenames:
        if filename[-11:] == 'ar_1001.csv':
            cip.append(os.path.join(root,filename))

In [281]:
len(cip)

4072

In [282]:
tempar = np.genfromtxt(cip[0])
tempar.shape[0]

1000

In [283]:
valar = np.zeros([len(cip),tempar.shape[0]])
for i in range(len(cip)):
    valar[i,:] = np.genfromtxt(cip[i], delimiter=',')    

In [284]:
cip[i][-28:-13]

'1484760\\1500861'

In [285]:
#D_out = 441
# if not(os.path.isfile('tmean.csv') and os.path.isfile(mainpath+'/sh.csv')):

landmarks_frame = pd.DataFrame(data=valar,index=range(len(cip)),\
                               columns=['f'+str(i) for i in range(tempar.shape[0])])
landmarks_frame.insert(0, 'file_name', \
                       [cip[i][-28:-13] for i in range(len(cip))])
landmarks_frame.to_csv(r'D:/seva/598test/train/Far_1001.csv', index=False)


## Creating csv for F_N2 only for val

In [286]:
cip = []
mainpath = r'D:\seva\598_processing\val' 
for root, directories, filenames in os.walk(mainpath): 
    for filename in filenames:
        if filename[-11:] == 'ar_1001.csv':
            cip.append(os.path.join(root,filename))

In [287]:
tempar = np.genfromtxt(cip[0])
tempar.shape[0]

1000

In [288]:
valar = np.zeros([len(cip),tempar.shape[0]])
for i in range(len(cip)):
    valar[i,:] = np.genfromtxt(cip[i], delimiter=',')    

In [289]:
cip[i][-28:-13]

'1484726\\1493207'

In [290]:
#D_out = 441
# if not(os.path.isfile('tmean.csv') and os.path.isfile(mainpath+'/sh.csv')):

landmarks_frame = pd.DataFrame(data=valar,index=range(len(cip)),\
                               columns=['f'+str(i) for i in range(tempar.shape[0])])
landmarks_frame.insert(0, 'file_name', \
                       [cip[i][-28:-13] for i in range(len(cip))])
landmarks_frame.to_csv(r'D:/seva/598test/val/Far_1001.csv', index=False)


## search of the min max of the sh amplitudes

In [20]:
data_dir

'D:/seva/598_processing'

In [16]:
# cip = []
# mainpath = data_dir 
# for root, directories, filenames in os.walk(mainpath): 
#     for filename in filenames:
#         if filename[-6:] == 'F_.csv':
#             cip.append(os.path.join(root,filename))

In [17]:
len(cip)

5270

In [18]:
cip[0]

'D:/seva/598_processing\\train\\1484727\\1493208_F_.csv'

In [19]:
a = np.genfromtxt(cip[2], delimiter=',')
a.shape

(34568,)

In [20]:
# maxsize = 0
# for i in cip:
#     if len(np.genfromtxt(i, delimiter=','))>maxsize:
#         maxsize = len(np.genfromtxt(i, delimiter=','))

In [21]:
maxsize

NameError: name 'maxsize' is not defined

In [22]:
# F = np.zeros([len(cip),maxsize])
# for i in range(len(cip)):
#     tempar = np.genfromtxt(cip[i], delimiter=',')
#     F[i,:] = np.concatenate((tempar, np.zeros([maxsize-tempar.shape[0]])), axis=0)
    

In [23]:
#numpy.savetxt("Fparameters.csv", labels, delimiter=",")

In [24]:
tmean = np.zeros([4,maxsize])
tmean[0,:] = np.mean(labels, axis = 0)
tmean[1,:] = np.std(labels, axis = 0)
tmean[2,:] = np.min(labels, axis = 0)
tmean[3,:] = np.max(labels, axis = 0)
numpy.savetxt("Fparameters-mean.csv", tmean, delimiter=",")

NameError: name 'maxsize' is not defined

In [25]:
#D_out = 441
# if not(os.path.isfile('tmean.csv') and os.path.isfile(mainpath+'/sh.csv')):

landmarks_frame = pd.DataFrame(data=F,index=range(len(cip)),\
                               columns=['f'+str(i) for i in range(maxsize)])
landmarks_frame.insert(0, 'file_name', \
                       [cip[i][-22:-7] for i in range(len(cip))])
landmarks_frame.to_csv(mainpath+'/Fparameters.csv', index=False)


NameError: name 'F' is not defined

In [ ]:
 #           Minmax3Dimage((0.60117054538415,110.972068294924)),\
#

## Finding max and min of _F_

In [48]:
cip = []
#mainpath = r'D:\seva\598_processing'
#mainpath = '/p/home/jusers/cherepashkin1/jureca/cherepashkin1/phenoseed/598/' 
mainpath = '/p/home/jusers/cherepashkin1/jureca/cherepashkin1/phenoseed_csv/598csv/'
for root, directories, filenames in os.walk(mainpath): 
    for filename in filenames:
        if 'Far_500_prenormalized.csv' in filename:
            cip.append(os.path.join(root,filename))

In [49]:
len(cip)

5270

In [50]:
mx = 0
mn = 100
for i in cip:
    tempar = np.genfromtxt(i, delimiter = ',')
    if np.max(tempar)>mx:
        mx = np.max(tempar)
    if np.min(tempar)<mn:
        mn = np.min(tempar)

In [47]:
mn, mx

(6.67855974495566, 70.8217880008657)

In [51]:
mn, mx

(2.6897299652941, 102.121738007844)

# Search for min max of ply values

In [2]:
import os
import numpy as np
import open3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [1]:
pwd

'/p/home/jusers/cherepashkin1/jureca/circles'

In [3]:
cip = []
mainpath = '/p/home/jusers/cherepashkin1/jureca/cherepashkin1/phenoseed/598/' 
for root, directories, filenames in os.walk(mainpath): 
    for filename in filenames:
        if 'Surface.ply' in filename:
            cip.append(os.path.join(root,filename))

In [4]:
minv = np.array([100, 100, 100])
maxv = np.array([0, 0, 0])
for i in range(len(cip)):
    pcd = open3d.io.read_point_cloud(cip[i])
    img = np.asarray(pcd.points)
    img -= np.mean(img,0)
    minc = np.min(img, axis=0)
    maxc = np.max(img, axis=0)
    for j in range(3):
        if minc[j] < minv[j]:
            minv[j] = minc[j]
        if maxc[j] > maxv[j]:
            maxv[j] = maxc[j]

In [5]:
minv, maxv

(array([-99, -68, -94]), array([101,  68,  95]))

In [7]:
maxv - minv

array([200, 136, 189])

In [6]:
minv*0.05, maxv*0.05

(array([-4.95, -3.4 , -4.7 ]), array([5.05, 3.4 , 4.75]))

In [30]:
img.shape

(19907, 3)

In [29]:
minv, maxv

(array([29,  1,  4]), array([240, 138, 243]))

In [25]:
minv

array([44,  1, 71])

In [26]:
maxv

array([210,  94, 231])

In [17]:
list(minv > [0, 0, 0]) == True

False

In [33]:
np.floor(5/2).astype(int)

2

In [38]:
dir1 = ('/p/home/jusers/cherepashkin1/jureca/'
    'cherepashkin1/598test/plot_output/')

In [39]:
dir1

'/p/home/jusers/cherepashkin1/jureca/cherepashkin1/598test/plot_output/'

# Putting all F_N.csv to one file for 598csv9 and 598csv11

In [5]:
import os
import numpy as np

In [17]:
cip = []
##mainpath = r'D:\seva\598_processing\train' 
for j in ['9', '11']:
    mainpath = r'D:/cherepashkin1/phenoseed_csv/598csv'+j 
    for root, directories, filenames in os.walk(mainpath): 
        for filename in filenames:
            if 'F_N.csv' in filename:
                cip.append(os.path.join(root,filename))
    F_Nar = np.zeros([len(cip),441])
    for i in range(len(cip)):
    #     print(cip)
    #     print(np.genfromtxt(cip[i], delimiter=',').shape)
        F_Nar[i,:] = np.genfromtxt(cip[i], delimiter=',')
        d1 = np.random.random(size = (1000,20))
d2 = np.random.random(size = (1000,200))
hf = h5py.File('data.h5', 'w')
hf.create_dataset('dataset_1', data=d1)
    np.savetxt('D:/cherepashkin1/phenoseed_csv/598csv'+j+'_F_N.csv', F_Nar, delimiter = ',')

In [22]:
# cip = []
##mainpath = r'D:\seva\598_processing\train' 
for j in ['9', '11']:
# d2 = np.random.random(size = (1000,200))
    hf = h5py.File('D:/cherepashkin1/phenoseed_csv/598csv'+j+'_F_N.h5', 'w')
    hf.create_dataset('dataset', data=np.genfromtxt('D:/cherepashkin1/phenoseed_csv/598csv'+j+'_F_N.csv', delimiter =','))
#     np.savetxt('D:/cherepashkin1/phenoseed_csv/598csv'+j+'_F_N.csv', F_Nar, delimiter = ',')

In [19]:
import h5py

In [20]:
d1 = np.random.random(size = (1000,20))
d2 = np.random.random(size = (1000,200))
hf = h5py.File('data.h5', 'w')
hf.create_dataset('dataset_1', data=d1)
hf.create_dataset('dataset_2', data=d2)
hf.close()

In [21]:
np.savetxt('d1', d1, delimiter = ',')
np.savetxt('d2', d2, delimiter = ',')

In [ ]:
import os

In [15]:
# cip = []
mainpath = r'D:/cherepashkin1/phenoseed/598'
for root, directories, filenames in os.walk(mainpath): 
    for filename in filenames:
        f1 = os.path.join(root,filename).split('\\')
        print(os.path.join(f1[0],f1[1]))
#         hf = h5py.File(os.path.join(f1[0],f1[1])
#                                     ,'data.h5', 'w')
#         bigimage = np.zeros([36,1800,1000])
#         for i in range(36):
#             if 'rotation'+str(i).zfill(3) in filename:
#                 bigimage[i]=np.asarray(io.imread(os.path.join(root,filename)))

D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenoseed/598\1484717
D:/cherepashkin1/phenosee

# making dataset for every seed one file

In [11]:
folders = []
mainpath = r'D:/cherepashkin1/phenoseed/598'
for root, directories, filenames in os.walk(mainpath): 
#     print(folders)
    folders = directories
    break
#     for filename in filenames:
#         if '.csv' in filename:
#             cip.append(os.path.join(root,filename))

In [12]:
print(folders)

['1484717', '1484718', '1484719', '1484720', '1484721', '1484722', '1484723', '1484724', '1484725', '1484726', '1484727', '1484728', '1484729', '1484730', '1484731', '1484732', '1484733', '1484734', '1484735', '1484736', '1484737', '1484738', '1484739', '1484740', '1484741', '1484742', '1484743', '1484744', '1484745', '1484746', '1484747', '1484748', '1484749', '1484750', '1484751', '1484752', '1484753', '1484754', '1484755', '1484756', '1484757', '1484758', '1484759', '1484760']


In [3]:
import os

In [8]:
for root, directories, filenames in os.walk("D:/cherepashkin1/phenoseed/598h5"): 
    if root.count('\\') == 1:
        os.mkdir(root.replace('598h5','598empty_first_level'))
        print(root)

D:/cherepashkin1/phenoseed/598h5\1484717
D:/cherepashkin1/phenoseed/598h5\1484718
D:/cherepashkin1/phenoseed/598h5\1484719
D:/cherepashkin1/phenoseed/598h5\1484720
D:/cherepashkin1/phenoseed/598h5\1484721
D:/cherepashkin1/phenoseed/598h5\1484722
D:/cherepashkin1/phenoseed/598h5\1484723
D:/cherepashkin1/phenoseed/598h5\1484724
D:/cherepashkin1/phenoseed/598h5\1484725
D:/cherepashkin1/phenoseed/598h5\1484726
D:/cherepashkin1/phenoseed/598h5\1484727
D:/cherepashkin1/phenoseed/598h5\1484728
D:/cherepashkin1/phenoseed/598h5\1484729
D:/cherepashkin1/phenoseed/598h5\1484730
D:/cherepashkin1/phenoseed/598h5\1484731
D:/cherepashkin1/phenoseed/598h5\1484732
D:/cherepashkin1/phenoseed/598h5\1484733
D:/cherepashkin1/phenoseed/598h5\1484734
D:/cherepashkin1/phenoseed/598h5\1484735
D:/cherepashkin1/phenoseed/598h5\1484736
D:/cherepashkin1/phenoseed/598h5\1484737
D:/cherepashkin1/phenoseed/598h5\1484738
D:/cherepashkin1/phenoseed/598h5\1484739
D:/cherepashkin1/phenoseed/598h5\1484740
D:/cherepashkin1